services:
  _defaults:
    autowire: true
    autoconfigure: true

  Adimeo\Logger\Services\LogManager:
    arguments:
      - '%env(ALS_ENABLED_DEV)%'
      - '%env(ALS_ELS_HOST)%'
      - '%env(ALS_ELS_INDEX)%'
      - '%env(APP_ENV)%'

  Adimeo\Logger\EventListener\LogIndexer:
    arguments:
        - '@Symfony\Component\Security\Core\Security'
        - '@Adimeo\Logger\Services\LogManager'
        - '@Symfony\Component\EventDispatcher\EventDispatcherInterface'

    tags:
      - { name: doctrine.event_listener, event: onFlush }